frany_bundles_login_register:
    pattern:  /register
    defaults: { _controller: FranyBundlesLoginBundle:Login:register }

frany_bundles_login_home:
    path: /
    defaults: { _controller: FranyBundlesLoginBundle:Home:home }